# Generated by Django 5.1.5 on 2025-01-15 15:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('comentario', models.TextField(verbose_name='Comentario que ha dejado en la web')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creacion')),
                ('contactado', models.BooleanField(default=False, verbose_name='¿Se ha contactado con él?')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
            },
        ),
    ]
