# Generated by Django 5.1.5 on 2025-01-15 17:34

import thumbnails.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_image',
            field=thumbnails.fields.ImageField(blank=True, null=True, upload_to='post/images/', verbose_name='Portada del post'),
        ),
    ]
